//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 05:42:21 PM MEZ 
//


package at.gv.e_government.reference.namespace.persondata._20020228_;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefinedAlternativeNameTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DefinedAlternativeNameTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ArtistName"/&gt;
 *     &lt;enumeration value="NickName"/&gt;
 *     &lt;enumeration value="FormerName"/&gt;
 *     &lt;enumeration value="Alias"/&gt;
 *     &lt;enumeration value="MaidenName"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DefinedAlternativeNameTypeType")
@XmlEnum
public enum DefinedAlternativeNameTypeType {

    @XmlEnumValue("ArtistName")
    ARTIST_NAME("ArtistName"),
    @XmlEnumValue("NickName")
    NICK_NAME("NickName"),
    @XmlEnumValue("FormerName")
    FORMER_NAME("FormerName"),
    @XmlEnumValue("Alias")
    ALIAS("Alias"),
    @XmlEnumValue("MaidenName")
    MAIDEN_NAME("MaidenName");
    private final String value;

    DefinedAlternativeNameTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DefinedAlternativeNameTypeType fromValue(String v) {
        for (DefinedAlternativeNameTypeType c: DefinedAlternativeNameTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
