/*
* Copyright 2008 Federal Chancellery Austria and
* Graz University of Technology
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.21 at 09:43:54 AM GMT 
//


package at.gv.e_government.reference.namespace.persondata._20020228_;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefinedRelationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DefinedRelationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="family:Parent"/>
 *     &lt;enumeration value="family:Child"/>
 *     &lt;enumeration value="family:Sibling"/>
 *     &lt;enumeration value="family:Grandparent"/>
 *     &lt;enumeration value="family:Grandchild"/>
 *     &lt;enumeration value="family:Spouse"/>
 *     &lt;enumeration value="function:LegalGuardian"/>
 *     &lt;enumeration value="function:IsGuardedBy"/>
 *     &lt;enumeration value="function:Cohabitant"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DefinedRelationType")
@XmlEnum
public enum DefinedRelationType {

    @XmlEnumValue("family:Parent")
    FAMILY_PARENT("family:Parent"),
    @XmlEnumValue("family:Child")
    FAMILY_CHILD("family:Child"),
    @XmlEnumValue("family:Sibling")
    FAMILY_SIBLING("family:Sibling"),
    @XmlEnumValue("family:Grandparent")
    FAMILY_GRANDPARENT("family:Grandparent"),
    @XmlEnumValue("family:Grandchild")
    FAMILY_GRANDCHILD("family:Grandchild"),
    @XmlEnumValue("family:Spouse")
    FAMILY_SPOUSE("family:Spouse"),
    @XmlEnumValue("function:LegalGuardian")
    FUNCTION_LEGAL_GUARDIAN("function:LegalGuardian"),
    @XmlEnumValue("function:IsGuardedBy")
    FUNCTION_IS_GUARDED_BY("function:IsGuardedBy"),
    @XmlEnumValue("function:Cohabitant")
    FUNCTION_COHABITANT("function:Cohabitant");
    private final String value;

    DefinedRelationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DefinedRelationType fromValue(String v) {
        for (DefinedRelationType c: DefinedRelationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
