//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 05:42:21 PM MEZ 
//


package at.gv.e_government.reference.namespace.persondata._20020228_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TelcomNumberListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TelcomNumberListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://reference.e-government.gv.at/namespace/persondata/20020228#}Telephone" minOccurs="0"/>
 *         &lt;element ref="{http://reference.e-government.gv.at/namespace/persondata/20020228#}Mobile" minOccurs="0"/>
 *         &lt;element ref="{http://reference.e-government.gv.at/namespace/persondata/20020228#}Fax" minOccurs="0"/>
 *         &lt;element ref="{http://reference.e-government.gv.at/namespace/persondata/20020228#}Pager" minOccurs="0"/>
 *         &lt;element ref="{http://reference.e-government.gv.at/namespace/persondata/20020228#}TTYTDD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TelcomNumberListType", propOrder = {
    "telephone",
    "mobile",
    "fax",
    "pager",
    "ttytdd"
})
public class TelcomNumberListType {

    @XmlElement(name = "Telephone")
    protected TelcomNumberType telephone;
    @XmlElement(name = "Mobile")
    protected MobileTelcomNumberType mobile;
    @XmlElement(name = "Fax")
    protected TelcomNumberType fax;
    @XmlElement(name = "Pager")
    protected TelcomNumberType pager;
    @XmlElement(name = "TTYTDD")
    protected TelcomNumberType ttytdd;

    /**
     * Gets the value of the telephone property.
     * 
     * @return
     *     possible object is
     *     {@link TelcomNumberType }
     *     
     */
    public TelcomNumberType getTelephone() {
        return telephone;
    }

    /**
     * Sets the value of the telephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelcomNumberType }
     *     
     */
    public void setTelephone(TelcomNumberType value) {
        this.telephone = value;
    }

    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link MobileTelcomNumberType }
     *     
     */
    public MobileTelcomNumberType getMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link MobileTelcomNumberType }
     *     
     */
    public void setMobile(MobileTelcomNumberType value) {
        this.mobile = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link TelcomNumberType }
     *     
     */
    public TelcomNumberType getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelcomNumberType }
     *     
     */
    public void setFax(TelcomNumberType value) {
        this.fax = value;
    }

    /**
     * Gets the value of the pager property.
     * 
     * @return
     *     possible object is
     *     {@link TelcomNumberType }
     *     
     */
    public TelcomNumberType getPager() {
        return pager;
    }

    /**
     * Sets the value of the pager property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelcomNumberType }
     *     
     */
    public void setPager(TelcomNumberType value) {
        this.pager = value;
    }

    /**
     * Gets the value of the ttytdd property.
     * 
     * @return
     *     possible object is
     *     {@link TelcomNumberType }
     *     
     */
    public TelcomNumberType getTTYTDD() {
        return ttytdd;
    }

    /**
     * Sets the value of the ttytdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelcomNumberType }
     *     
     */
    public void setTTYTDD(TelcomNumberType value) {
        this.ttytdd = value;
    }

}
