
package at.gv.egiz.stal.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "STALService", targetNamespace = "http://www.egiz.gv.at/wsdl/stal")
//, wsdlLocation = "file:/home/clemens/workspace/mocca/BKUOnline/src/main/webapp/WEB-INF/wsdl/stal-service.wsdl")
public class STALService
    extends Service
{

//    private final static URL STALSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(at.gv.egiz.stal.service.STALService.class.getName());

//    static {
//        URL url = null;
//        try {
//            URL baseUrl;
//            baseUrl = at.gv.egiz.stal.service.STALService.class.getResource(".");
//            url = new URL(baseUrl, "file:/home/clemens/workspace/mocca/BKUOnline/src/main/webapp/WEB-INF/wsdl/stal-service.wsdl");
//        } catch (MalformedURLException e) {
//            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/clemens/workspace/mocca/BKUOnline/src/main/webapp/WEB-INF/wsdl/stal-service.wsdl', retrying as a local file");
//            logger.warning(e.getMessage());
//        }
//        STALSERVICE_WSDL_LOCATION = url;
//    }

    public STALService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

//    public STALService() {
//        super(STALSERVICE_WSDL_LOCATION, new QName("http://www.egiz.gv.at/wsdl/stal", "STALService"));
//    }

    /**
     * 
     * @return
     *     returns STALPortType
     */
    @WebEndpoint(name = "STALPort")
    public STALPortType getSTALPort() {
        return super.getPort(new QName("http://www.egiz.gv.at/wsdl/stal", "STALPort"), STALPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns STALPortType
     */
//    @WebEndpoint(name = "STALPort")
//    public STALPortType getSTALPort(WebServiceFeature... features) {
//        return super.getPort(new QName("http://www.egiz.gv.at/wsdl/stal", "STALPort"), STALPortType.class, features);
//    }

}
