/*
 * Copyright 2011 by Graz University of Technology, Austria
 * MOCCA has been developed by the E-Government Innovation Center EGIZ, a joint
 * initiative of the Federal Chancellery Austria and Graz University of Technology.
 *
 * Licensed under the EUPL, Version 1.1 or - as soon they will be approved by
 * the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * http://www.osor.eu/eupl/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 *
 * This product combines work with different licenses. See the "NOTICE" text
 * file for details on the various modules and licenses.
 * The "NOTICE" text file is part of the distribution. Any derivative works
 * that you distribute must include a readable copy of the "NOTICE" text file.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.21 at 09:43:54 AM GMT 
//


package at.buergerkarte.namespaces.personenbindung._20020506_;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import at.gv.e_government.reference.namespace.persondata._20020228_.AbstractPersonType;
import org.w3._2000._09.xmldsig_.KeyValueType;


/**
 * <p>Java class for CompressedIdentityLinkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompressedIdentityLinkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IssuerTemplate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AssertionID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IssueInstant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PersonData" type="{http://reference.e-government.gv.at/namespace/persondata/20020228#}AbstractPersonType"/>
 *         &lt;element name="CitizenPublicKey" type="{http://www.w3.org/2000/09/xmldsig#}KeyValueType" maxOccurs="unbounded"/>
 *         &lt;element name="SignatureValue" type="{http://www.w3.org/2000/09/xmldsig#}CryptoBinary"/>
 *         &lt;element name="ReferenceDigest" type="{http://www.w3.org/2000/09/xmldsig#}CryptoBinary" minOccurs="0"/>
 *         &lt;element name="ReferenceManifestDigest" type="{http://www.w3.org/2000/09/xmldsig#}CryptoBinary" minOccurs="0"/>
 *         &lt;element name="ManifestReferenceDigest" type="{http://www.w3.org/2000/09/xmldsig#}CryptoBinary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompressedIdentityLinkType", propOrder = {
    "issuerTemplate",
    "assertionID",
    "issueInstant",
    "personData",
    "citizenPublicKey",
    "signatureValue",
    "referenceDigest",
    "referenceManifestDigest",
    "manifestReferenceDigest"
})
public class CompressedIdentityLinkType {

    @XmlElement(name = "IssuerTemplate", required = true)
    protected String issuerTemplate;
    @XmlElement(name = "AssertionID", required = true)
    protected String assertionID;
    @XmlElement(name = "IssueInstant", required = true)
    protected String issueInstant;
    @XmlElement(name = "PersonData", required = true)
    protected AbstractPersonType personData;
    @XmlElement(name = "CitizenPublicKey", required = true)
    protected List<KeyValueType> citizenPublicKey;
    @XmlElement(name = "SignatureValue", required = true)
    protected byte[] signatureValue;
    @XmlElement(name = "ReferenceDigest")
    protected byte[] referenceDigest;
    @XmlElement(name = "ReferenceManifestDigest")
    protected byte[] referenceManifestDigest;
    @XmlElement(name = "ManifestReferenceDigest")
    protected byte[] manifestReferenceDigest;

    /**
     * Gets the value of the issuerTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerTemplate() {
        return issuerTemplate;
    }

    /**
     * Sets the value of the issuerTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerTemplate(String value) {
        this.issuerTemplate = value;
    }

    /**
     * Gets the value of the assertionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssertionID() {
        return assertionID;
    }

    /**
     * Sets the value of the assertionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssertionID(String value) {
        this.assertionID = value;
    }

    /**
     * Gets the value of the issueInstant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueInstant() {
        return issueInstant;
    }

    /**
     * Sets the value of the issueInstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueInstant(String value) {
        this.issueInstant = value;
    }

    /**
     * Gets the value of the personData property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractPersonType }
     *     
     */
    public AbstractPersonType getPersonData() {
        return personData;
    }

    /**
     * Sets the value of the personData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractPersonType }
     *     
     */
    public void setPersonData(AbstractPersonType value) {
        this.personData = value;
    }

    /**
     * Gets the value of the citizenPublicKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citizenPublicKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitizenPublicKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValueType }
     * 
     * 
     */
    public List<KeyValueType> getCitizenPublicKey() {
        if (citizenPublicKey == null) {
            citizenPublicKey = new ArrayList<KeyValueType>();
        }
        return this.citizenPublicKey;
    }

    /**
     * Gets the value of the signatureValue property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSignatureValue() {
        return signatureValue;
    }

    /**
     * Sets the value of the signatureValue property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSignatureValue(byte[] value) {
        this.signatureValue = ((byte[]) value);
    }

    /**
     * Gets the value of the referenceDigest property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getReferenceDigest() {
        return referenceDigest;
    }

    /**
     * Sets the value of the referenceDigest property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setReferenceDigest(byte[] value) {
        this.referenceDigest = ((byte[]) value);
    }

    /**
     * Gets the value of the referenceManifestDigest property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getReferenceManifestDigest() {
        return referenceManifestDigest;
    }

    /**
     * Sets the value of the referenceManifestDigest property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setReferenceManifestDigest(byte[] value) {
        this.referenceManifestDigest = ((byte[]) value);
    }

    /**
     * Gets the value of the manifestReferenceDigest property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getManifestReferenceDigest() {
        return manifestReferenceDigest;
    }

    /**
     * Sets the value of the manifestReferenceDigest property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setManifestReferenceDigest(byte[] value) {
        this.manifestReferenceDigest = ((byte[]) value);
    }

}
