//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.01 at 04:42:31 PM CEST 
//


package at.buergerkarte.namespaces.securitylayer._1_2_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CMSDataObjectOptionalMetaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CMSDataObjectOptionalMetaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MetaInfo" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}MetaInfoType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Content" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}Base64OptRefContentType"/&gt;
 *           &lt;element name="DigestAndRef" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}DigestAndRefType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="ExcludedByteRange" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}ExcludedByteRangeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CMSDataObjectOptionalMetaType", propOrder = {
    "metaInfo",
    "content",
    "digestAndRef",
    "excludedByteRange"
})
@XmlSeeAlso({
  CMSReferenceObject.class,
  CMSDataObjectRequiredMetaType.class
})
public class CMSDataObjectOptionalMetaType {

    @XmlElement(name = "MetaInfo")
    protected MetaInfoType metaInfo;
    @XmlElement(name = "Content", required = true)
    protected Base64OptRefContentType content;
    @XmlElement(name = "DigestAndRef")
    protected DigestAndRefType digestAndRef;
    @XmlElement(name = "ExcludedByteRange")
    protected ExcludedByteRangeType excludedByteRange;

    /**
     * Gets the value of the metaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MetaInfoType }
     *     
     */
    public MetaInfoType getMetaInfo() {
        return metaInfo;
    }

    /**
     * Sets the value of the metaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaInfoType }
     *     
     */
    public void setMetaInfo(MetaInfoType value) {
        this.metaInfo = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Base64OptRefContentType }
     *     
     */
    public Base64OptRefContentType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64OptRefContentType }
     *     
     */
    public void setContent(Base64OptRefContentType value) {
        this.content = value;
    }
    
    /**
     * Ruft den Wert der digestAndRef-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link DigestAndRefType }
     *     
     */
    public DigestAndRefType getDigestAndRef() {
        return digestAndRef;
    }

    /**
     * Legt den Wert der digestAndRef-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link DigestAndRefType }
     *     
     */
    public void setDigestAndRef(DigestAndRefType value) {
        this.digestAndRef = value;
    }

    /**
     * Gets the value of the excludedByteRange property.
     * 
     * @return
     *     possible object is
     *     {@link ExcludedByteRangeType }
     *     
     */
    public ExcludedByteRangeType getExcludedByteRange() {
        return excludedByteRange;
    }

    /**
     * Sets the value of the excludedByteRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExcludedByteRangeType }
     *     
     */
    public void setExcludedByteRange(ExcludedByteRangeType value) {
        this.excludedByteRange = value;
    }

}
