//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 07:38:37 PM CET 
//


package at.buergerkarte.namespaces.securitylayer._1_2_3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserConfirmationSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UserConfirmationSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="info"/>
 *     &lt;enumeration value="confirm"/>
 *     &lt;enumeration value="confirmWithSecret"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UserConfirmationSimpleType")
@XmlEnum
public enum UserConfirmationSimpleType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("info")
    INFO("info"),
    @XmlEnumValue("confirm")
    CONFIRM("confirm"),
    @XmlEnumValue("confirmWithSecret")
    CONFIRM_WITH_SECRET("confirmWithSecret");
    private final String value;

    UserConfirmationSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UserConfirmationSimpleType fromValue(String v) {
        for (UserConfirmationSimpleType c: UserConfirmationSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
