<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Web Service Description for MOA SP/SS 1.4
  modified for BKU2 testing
-->
<definitions name="MOA" 
    targetNamespace="http://reference.e-government.gv.at/namespace/moa/wsdl/20020822#"
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:tns="http://reference.e-government.gv.at/namespace/moa/wsdl/20020822#" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:moa="http://reference.e-government.gv.at/namespace/moa/20020822#" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <types>
        <xsd:schema targetNamespace="http://reference.e-government.gv.at/namespace/moa/wsdl/20020822#">
            <xsd:import namespace="http://reference.e-government.gv.at/namespace/moa/20020822#" schemaLocation="MOA-SPSS-1.3.xsd"/>
        </xsd:schema>
    </types>
    
    <message name="VerifyXMLSignatureInput">
        <part name="body" element="moa:VerifyXMLSignatureRequest"/>
    </message>
    <message name="VerifyXMLSignatureOutput">
        <part name="body" element="moa:VerifyXMLSignatureResponse"/>
    </message>
    <message name="MOAFault">
        <part name="body" element="moa:ErrorResponse"/>
    </message>
    <portType name="SignatureVerificationPortType">
        <operation name="verifyXMLSignature">
            <input message="tns:VerifyXMLSignatureInput"/>
            <output message="tns:VerifyXMLSignatureOutput"/>
            <fault name="MOAFault" message="tns:MOAFault"/>
        </operation>
    </portType>
    <binding name="SignatureVerificationBinding" type="tns:SignatureVerificationPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="verifyXMLSignature">
            <soap:operation soapAction="urn:VerifyXMLSignatureAction"/>
            <input>
                <soap:body use="literal" namespace="http://reference.e-government.gv.at/namespace/moa/20020822#"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://reference.e-government.gv.at/namespace/moa/20020822#"/>
            </output>
            <fault name="MOAFault">
                <soap:fault name="MOAFault" use="literal" namespace="http://reference.e-government.gv.at/namespace/moa/20020822#"/>
            </fault>
        </operation>
    </binding>
    <service name="SignatureVerificationService">
        <port name="SignatureVerificationPort" binding="tns:SignatureVerificationBinding">
            <soap:address location="http://localhost:8088/moa-spss/services/SignatureVerification"/>
        </port>
    </service>
</definitions>
