/*
* Copyright 2008 Federal Chancellery Austria and
* Graz University of Technology
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.25 at 10:41:37 AM GMT 
//


package at.buergerkarte.namespaces.securitylayer._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecryptCMSRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecryptCMSRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CMSMessage" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="EncryptedContent" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}CMSEncryptedContentType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ReturnResult" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}ReturnResultType" default="xml" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecryptCMSRequestType", propOrder = {
    "cmsMessage",
    "encryptedContent"
})
public class DecryptCMSRequestType {

    @XmlElement(name = "CMSMessage", required = true)
    protected byte[] cmsMessage;
    @XmlElement(name = "EncryptedContent")
    protected CMSEncryptedContentType encryptedContent;
    @XmlAttribute(name = "ReturnResult")
    protected ReturnResultType returnResult;

    /**
     * Gets the value of the cmsMessage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCMSMessage() {
        return cmsMessage;
    }

    /**
     * Sets the value of the cmsMessage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCMSMessage(byte[] value) {
        this.cmsMessage = ((byte[]) value);
    }

    /**
     * Gets the value of the encryptedContent property.
     * 
     * @return
     *     possible object is
     *     {@link CMSEncryptedContentType }
     *     
     */
    public CMSEncryptedContentType getEncryptedContent() {
        return encryptedContent;
    }

    /**
     * Sets the value of the encryptedContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CMSEncryptedContentType }
     *     
     */
    public void setEncryptedContent(CMSEncryptedContentType value) {
        this.encryptedContent = value;
    }

    /**
     * Gets the value of the returnResult property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnResultType }
     *     
     */
    public ReturnResultType getReturnResult() {
        if (returnResult == null) {
            return ReturnResultType.XML;
        } else {
            return returnResult;
        }
    }

    /**
     * Sets the value of the returnResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnResultType }
     *     
     */
    public void setReturnResult(ReturnResultType value) {
        this.returnResult = value;
    }

}
