//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.03 at 03:06:11 PM GMT 
//


package at.gv.egiz.bku.accesscontrol.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ChainRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RuleAction">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="allow"/>
 *               &lt;enumeration value="deny"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chainRef",
    "ruleAction"
})
@XmlRootElement(name = "Action")
public class Action {

    @XmlElement(name = "ChainRef")
    protected String chainRef;
    @XmlElement(name = "RuleAction")
    protected String ruleAction;

    /**
     * Gets the value of the chainRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChainRef() {
        return chainRef;
    }

    /**
     * Sets the value of the chainRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChainRef(String value) {
        this.chainRef = value;
    }

    /**
     * Gets the value of the ruleAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleAction() {
        return ruleAction;
    }

    /**
     * Sets the value of the ruleAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleAction(String value) {
        this.ruleAction = value;
    }

}
