/*
 * Copyright 2011 by Graz University of Technology, Austria
 * MOCCA has been developed by the E-Government Innovation Center EGIZ, a joint
 * initiative of the Federal Chancellery Austria and Graz University of Technology.
 *
 * Licensed under the EUPL, Version 1.1 or - as soon they will be approved by
 * the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * http://www.osor.eu/eupl/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 *
 * This product combines work with different licenses. See the "NOTICE" text
 * file for details on the various modules and licenses.
 * The "NOTICE" text file is part of the distribution. Any derivative works
 * that you distribute must include a readable copy of the "NOTICE" text file.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.21 at 09:30:44 AM GMT 
//


package org.w3._2001._04.xmldsig_more_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExplicitParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExplicitParamsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FieldParams" type="{http://www.w3.org/2001/04/xmldsig-more#}FieldParamsType"/>
 *         &lt;element name="CurveParams" type="{http://www.w3.org/2001/04/xmldsig-more#}CurveParamsType"/>
 *         &lt;element name="BasePointParams" type="{http://www.w3.org/2001/04/xmldsig-more#}BasePointParamsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExplicitParamsType", propOrder = {
    "fieldParams",
    "curveParams",
    "basePointParams"
})
public class ExplicitParamsType {

    @XmlElement(name = "FieldParams", required = true)
    protected FieldParamsType fieldParams;
    @XmlElement(name = "CurveParams", required = true)
    protected CurveParamsType curveParams;
    @XmlElement(name = "BasePointParams", required = true)
    protected BasePointParamsType basePointParams;

    /**
     * Gets the value of the fieldParams property.
     * 
     * @return
     *     possible object is
     *     {@link FieldParamsType }
     *     
     */
    public FieldParamsType getFieldParams() {
        return fieldParams;
    }

    /**
     * Sets the value of the fieldParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldParamsType }
     *     
     */
    public void setFieldParams(FieldParamsType value) {
        this.fieldParams = value;
    }

    /**
     * Gets the value of the curveParams property.
     * 
     * @return
     *     possible object is
     *     {@link CurveParamsType }
     *     
     */
    public CurveParamsType getCurveParams() {
        return curveParams;
    }

    /**
     * Sets the value of the curveParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurveParamsType }
     *     
     */
    public void setCurveParams(CurveParamsType value) {
        this.curveParams = value;
    }

    /**
     * Gets the value of the basePointParams property.
     * 
     * @return
     *     possible object is
     *     {@link BasePointParamsType }
     *     
     */
    public BasePointParamsType getBasePointParams() {
        return basePointParams;
    }

    /**
     * Sets the value of the basePointParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasePointParamsType }
     *     
     */
    public void setBasePointParams(BasePointParamsType value) {
        this.basePointParams = value;
    }

}
